import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { LoadingProvider } from "./_context/LoadingContext";
import { AuthProvider } from "./_context/AuthContext";
import { MessageProvider } from "./_context/MessageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FanStocks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <MessageProvider>
            <LoadingProvider>
              <div className="flex flex-col min-h-screen">
                <Header />
                {children}
              </div>
            </LoadingProvider>
          </MessageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
